name: Push to Docker registry

on:
  push:
    branches:
      - main
  release:
    types:
      - created

env:
  IMAGE_TAG: ${{ github.event.release.tag_name != '' && github.event.release.tag_name || 'latest' }}

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build docker image
        if: success()
        run: docker build -t "aoirint/twifavoritedl:${{ env.IMAGE_TAG }}" .

      - name: Deploy docker image
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push "aoirint/twifavoritedl:${{ env.IMAGE_TAG }}"

